@Lindiwe_HostAddress = http://localhost:5134

### Add new command
POST {{Lindiwe_HostAddress}}/commands
Accept: application/json
Content-Type: application/json

{
  "type": "echo",
  "payloadJson": "{\"message\":\"hello\"}"
}